#ifndef myoptions_h
#define myoptions_h

#define L10N_LANGUAGE     EN
/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,2,3,6,7,8,28,34,41,43,49,50,52,53,75,66&i=1,2,3,4,15,16,17,22,23,24,27,39,45,46,47,40&v=16,2,17,255,5,26,27,21,23,15,14,13,18,19,22,255 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */
#define ENC_INTERNALPULLUP false
#define ENC2_INTERNALPULLUP false
//DSP_MODEL==DSP_ST7789_240
#define DSP_MODEL   DSP_ST7789_240

#define SD_SPIPINS	12, 11, 13			/* SCK, MISO, MOSI */
#define SDC_CS		10

#define ROTATE_90			true
#define TFT_DC			16
#define TFT_CS			255
#define TFT_RST			17
//mosi
#define TFT_MOSI	18
#define TFT_SCK     8

#define I2S_DOUT	    5
#define I2S_LRC			27
#define BTN_UP		9
//#define BTN_CENTER		255
#define BTN_DOWN		21
#define BTN_MODE		14

#define VS1053_CS     255

#endif
